// <auto-generated />
using System;
using CognaAPI.Infra.Context;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace CognaAPI.Infra.Migrations
{
    [DbContext(typeof(CognaDbContext))]
    partial class CognaDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.6")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder, 1L, 1);

            modelBuilder.Entity("CognaAPI.Domain.Entidades.Todo", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<bool>("Concluido")
                        .HasColumnType("bit");

                    b.Property<DateTime>("Criado")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("DataLembrete")
                        .HasColumnType("datetime2");

                    b.Property<string>("Descricao")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("UltimaModificacao")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.ToTable("Todos");

                    b.HasData(
                        new
                        {
                            Id = new Guid("5aa6c1d0-0eb4-4dae-8813-08d9e2b4aa87"),
                            Concluido = false,
                            Criado = new DateTime(2022, 6, 16, 19, 8, 15, 853, DateTimeKind.Local).AddTicks(5853),
                            DataLembrete = new DateTime(2022, 6, 18, 19, 8, 15, 853, DateTimeKind.Local).AddTicks(5841),
                            Descricao = "Comprar Utensílios de cozinha"
                        },
                        new
                        {
                            Id = new Guid("03e68c0c-1164-43c9-6bb9-08d9e34472ad"),
                            Concluido = false,
                            Criado = new DateTime(2022, 6, 16, 19, 8, 15, 853, DateTimeKind.Local).AddTicks(5880),
                            DataLembrete = new DateTime(2022, 6, 17, 19, 8, 15, 853, DateTimeKind.Local).AddTicks(5879),
                            Descricao = "Fazer Macarronada"
                        },
                        new
                        {
                            Id = new Guid("69881eb1-b47e-4d56-6bc1-08d9e34472ad"),
                            Concluido = false,
                            Criado = new DateTime(2022, 6, 16, 19, 8, 15, 853, DateTimeKind.Local).AddTicks(5888),
                            DataLembrete = new DateTime(2022, 6, 21, 19, 8, 15, 853, DateTimeKind.Local).AddTicks(5887),
                            Descricao = "Buscar encomenda"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
